<?php


namespace app\index\controller;


use think\facade\View;

class BaseUc extends Base
{
    protected $payments;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = session('xwx_user_id');
        if (is_null($this->uid)){
            $this->redirect(url('/login'));
        }
        $this->payments = array();
        $this->payments['vip'] = config('payment.vip');
        $this->payments['money'] = config('payment.money');
        $this->payments['sign_rewards'] = config('payment.sign_rewards');
        $this->payments['login_rewards'] = config('payment.login_rewards');
        $this->payments['share_rewards']= config('payment.share_rewards');
        $this->payments['reg_reward'] = config('payment.reg_reward');
        $this->payments['bind_phone_rewards'] = config('payment.bind_phone_rewards');
        $this->payments['promotional_rewards_rate'] = config('payment.promotional_rewards_rate');
        View::assign('payments', $this->payments);
    }
}