<?php


namespace app\index\controller;


use think\db\concern\AggregateQuery;
use think\facade\View;

class Booklist extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        cookie('nav_switch', 'booklist'); //设置导航菜单active
    }

    public function index()
    {
        $area = input('area');
        if (empty($area)) {
            $area = -1;
        }
        $cate = input('cate');
        if (empty($cate)) {
            $cate = '全部';
        }
        $end = input('end');
        if (empty($end)) {
            $end = -1;
        }

        View::assign([
            'cate' => $cate,
            'area' => $area,
            'end' => $end,
        ]);
        return view($this->tpl);
    }
}