<?php


namespace app\admin\controller;

use app\BaseController;
use think\App;
use think\facade\Env;
use think\facade\View;

class BaseAdmin extends BaseController
{
    protected $prefix;
    protected $site;
    protected $end_point;
    protected $img_domain;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (session('xwx_admin') == null) {
            $this->redirect(adminurl('login/login'));
        }
        $this->prefix = Env::get('database.prefix');
        $this->site = config('site.domain');
        $this->end_point = config('seo.book_end_point');
        $this->img_domain = config('site.img_domain');
        View::assign([
            'prefix' => $this->prefix,
            'admin' => session('xwx_admin'),
            'site' => $this->site
        ]);
    }
}